"""altered guest table

Revision ID: 1052746e3fe6
Revises: 7e9634766053
Create Date: 2019-04-24 14:07:12.124985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1052746e3fe6'
down_revision = '7e9634766053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_guests', sa.Column('arrival_date', sa.Date(), nullable=True))
    op.add_column('tenant_guests', sa.Column('arrival_time', sa.Time(), nullable=True))
    op.drop_column('tenant_guests', 'time_to')
    op.drop_column('tenant_guests', 'time_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_guests', sa.Column('time_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenant_guests', sa.Column('time_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tenant_guests', 'arrival_time')
    op.drop_column('tenant_guests', 'arrival_date')
    # ### end Alembic commands ###
