"""added vehicle image to tenant vehicles table

Revision ID: 3199f253564d
Revises: d4b64e6de1a2
Create Date: 2019-05-15 13:40:54.645324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3199f253564d'
down_revision = 'd4b64e6de1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_vehicles', sa.Column('vehicle_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_vehicles', 'vehicle_image')
    # ### end Alembic commands ###
