"""changed column name

Revision ID: 7e9634766053
Revises: c112910c9905
Create Date: 2019-04-24 13:53:13.182601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9634766053'
down_revision = 'c112910c9905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_guests', sa.Column('guest_name', sa.String(length=128), nullable=True))
    op.drop_column('tenant_guests', 'tenant_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_guests', sa.Column('tenant_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('tenant_guests', 'guest_name')
    # ### end Alembic commands ###
