"""added emergency access table

Revision ID: a108db8340a8
Revises: 2fe35b98f75d
Create Date: 2019-05-24 12:30:47.820960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a108db8340a8'
down_revision = '2fe35b98f75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('access_date', sa.Date(), nullable=True),
    sa.Column('access_time', sa.Time(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tenant_vehicle_id'], ['tenant_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_access')
    # ### end Alembic commands ###
