"""added exclusive table

Revision ID: d4b64e6de1a2
Revises: 1052746e3fe6
Create Date: 2019-05-08 06:04:43.414249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b64e6de1a2'
down_revision = '1052746e3fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusive_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_prefix', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'tenant_guests', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'tenant_vehicles', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_vehicles', type_='foreignkey')
    op.drop_constraint(None, 'tenant_guests', type_='foreignkey')
    op.drop_table('exclusive_list')
    # ### end Alembic commands ###
